flat_teaching.Rmd:
  path: dev/flat_teaching.Rmd
  state: active
  R: R/preproces_data.R
  tests: []
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_teaching.Rmd
    vignette_name: Get started
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
