# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Plot Average Daily Gain (ADG) Growth Curves
#'
#' @description
#' Creates and optionally saves visualization plots for pig growth data based on ADG (Average Daily Gain) 
#' calculations. The function generates detailed growth curve plots with prediction intervals, outlier 
#' marking, and linear regression fits.
#'
#' @param data A list object returned by the `adg_get()` function, containing ADG data and related information.
#' @param responders Character vector specifying which pig IDs to include. Default is `NULL` (all responders).
#' @param locations Character vector specifying which locations to include. Default is `NULL` (all locations).
#' @param color_theme Character string specifying the color theme to use from the `ggsci` package. 
#'   Default is "d3". Available themes include: "npg", "aaas", "nejm", "lancet", "jama", "bjm", "jco", 
#'   "d3", "observable", "locuszoom", "igv", "cosmic", "uchicago", "startrek", "tron", "futurama", 
#'   "rickandmorty", "simpsons", "flatui", "frontiers", "ucscgb".
#' @param save_path Character string specifying the path to save plots. Default is `NULL` (plots not saved).
#' @param file_prefix Character string for the prefix of saved filenames. Default is "loc".
#' @param file_suffix Character string for the suffix of saved filenames. Default is `NULL` (automatically set to "grow").
#' @param dpi Numeric value for the resolution of saved plots. Default is 300.
#' @param device Character string specifying the file format for saved plots. Default is "png".
#'   Supported formats: "png", "pdf", "jpeg", "tiff".
#' @param quiet Logical. If TRUE, suppresses messages and warnings. Default: FALSE.
#'
#' @return A `data.table` containing:
#' \itemize{
#'   \item `location`: Location identifier
#'   \item `data`: List of data for each location
#'   \item `plot`: List of ggplot2 objects for each location
#' }
#'
#' @details
#' The plots created by `adg_plot` include:
#' \itemize{
#'   \item Weight over time scatter plots
#'   \item Linear regression prediction lines
#'   \item Prediction confidence interval bands
#'   \item Horizontal reference lines at key weight stages (30kg, 60kg, 120kg)
#'   \item Growth parameter annotations (slope, R² value, stage days, ADG value) for each pig
#'   \item Color differentiation between outliers and normal values
#' }
#'
#' @seealso
#' \code{\link{adg_get}} for calculating ADG data
#' \code{\link{clean_weight_get}} for cleaning and preparing weight data
#' \code{\link{preprocess_data}} for data preprocessing
#'
#' @importFrom ggplot2 ggplot aes geom_hline geom_ribbon geom_point geom_line facet_wrap scale_x_date 
#'   scale_y_continuous geom_text labs theme_bw theme element_blank element_text guides guide_legend ggsave
#' @importFrom data.table copy tstrsplit :=
#' @importFrom ggsci scale_color_npg scale_color_aaas scale_color_nejm scale_color_lancet scale_color_jama 
#'   scale_color_bmj scale_color_jco scale_color_d3 scale_color_observable scale_color_locuszoom 
#'   scale_color_igv scale_color_cosmic scale_color_uchicago scale_color_startrek scale_color_tron 
#'   scale_color_futurama scale_color_rickandmorty scale_color_simpsons scale_color_flatui 
#'   scale_color_frontiers scale_color_ucscgb
#' @importFrom cli cli_abort cli_alert_warning cli_alert_success cli_alert_info cli_process_start 
#'   cli_progress_bar cli_progress_update cli_progress_done cli_process_done cli_alert_danger
#' @importFrom purrr map map2
#'
#' @export
#' @examples
#' result_nedap <- preprocess_data(data = mintyr::nedap, station_type = "nedap", quiet = TRUE)
#' adg_result <- adg_get(result_nedap, my_break = c(30,120), quiet = TRUE)
#' res <- adg_plot(data = adg_result, save_path = tempdir(), location = "101", quiet = TRUE)
#' # Check exported files
#' list.files(path = tempdir(), pattern = "png", recursive = TRUE)
#' # Clean up exported files
#' files <- list.files(
#'   path = tempdir(),         # Default export directory
#'   pattern = "png",          # File type pattern to search
#'   recursive = TRUE,         # Search in subdirectories
#'   full.names = TRUE         # Return full file paths
#' )
#' file.remove(files)          # Remove all exported files
adg_plot <- function(data,
                     responders = NULL,
                     locations = NULL,
                     color_theme = "d3",
                     save_path = NULL,
                     file_prefix = "loc",
                     file_suffix = NULL,
                     dpi = 300,
                     device = "png",
                     quiet = FALSE) {

  # 定义处理函数，根据quiet参数决定是否抑制消息和警告
  process_fn <- if (quiet) {
    function(expr) suppressMessages(suppressWarnings(expr))
  } else {
    function(expr) expr
  }

  # 使用process_fn包装主要处理逻辑
  result <- process_fn({
    # 创建ADG图表
    adg_results <- create_adg_plots(
      data = data,
      responders = responders,
      locations = locations,
      color_theme = color_theme
    )

    # 如果提供了保存路径，则保存图表
    if (!is.null(save_path)) {
      save_plots(
        data = adg_results,
        save_path = save_path,
        plot_type = "adg",
        file_prefix = file_prefix,
        file_suffix = file_suffix,
        dpi = dpi,
        device = device
      )
    }

    # 返回结果
    adg_results
  })
  
  return(result)
}

validate_color_theme <- function(color_theme) {
  color_themes <- list(
    "npg" = ggsci::scale_color_npg,
    "aaas" = ggsci::scale_color_aaas,
    "nejm" = ggsci::scale_color_nejm,
    "lancet" = ggsci::scale_color_lancet,
    "jama" = ggsci::scale_color_jama,
    "bjm" = ggsci::scale_color_bmj,
    "jco" = ggsci::scale_color_jco,
    "d3" = ggsci::scale_color_d3,
    "observable" = ggsci::scale_color_observable,
    "locuszoom" = ggsci::scale_color_locuszoom,
    "igv" = ggsci::scale_color_igv,
    "cosmic" = ggsci::scale_color_cosmic,
    "uchicago" = ggsci::scale_color_uchicago,
    "startrek" = ggsci::scale_color_startrek,
    "tron" = ggsci::scale_color_tron,
    "futurama" = ggsci::scale_color_futurama,
    "rickandmorty" = ggsci::scale_color_rickandmorty,
    "simpsons" = ggsci::scale_color_simpsons,
    "flatui" = ggsci::scale_color_flatui,
    "frontiers" = ggsci::scale_color_frontiers,
    "ucscgb" = ggsci::scale_color_ucscgb
  )

  if (!color_theme %in% names(color_themes)) {
    cli::cli_abort(c(
      "x" = "Invalid color theme: {color_theme}",
      "i" = "Available themes: {paste(names(color_themes), collapse = ', ')}"
    ))
  }

  color_themes[[color_theme]]
}
validate_inputs <- function(data, data_type, responders, locations) {
  responder <- location <- NULL
  data <- data.table::copy(data)
  dataset_name <- paste0(data_type, "_data")
  main_data <- data[[dataset_name]]

  # 验证responders
  if (!is.null(responders)) {
    valid_responders <- responders %in% unique(main_data$responder)
    if (!all(valid_responders)) {
      invalid_resp <- responders[!valid_responders]
      cli::cli_alert_warning("Some responders not found: {.field {cli::col_red(invalid_resp)}}")
    }
  }

  # 验证locations
  if (!is.null(locations)) {
    valid_locations <- locations %in% unique(main_data$location)
    if (!all(valid_locations)) {
      invalid_loc <- locations[!valid_locations]
      cli::cli_alert_warning("Some locations not found: {.field {cli::col_red(invalid_loc)}}")
    }
  }

  # 过滤数据
  filtered_data <- main_data
  if (!is.null(responders)) filtered_data <- filtered_data[responder %in% responders]
  if (!is.null(locations)) filtered_data <- filtered_data[location %in% locations]

  if (nrow(filtered_data) == 0) {
    cli::cli_abort("No available data after filtering. Please check the parameter settings.")
  }

  list(data = data, filtered_data = filtered_data)
}
set_common_theme <- function(plot, title, y_lab, color_scale, legend_breaks, legend_labels) {
  plot +
    ggplot2::labs(title = title, y = y_lab) +
    color_scale(
      name = "Data Source:",
      breaks = legend_breaks,
      labels = legend_labels
    ) +
    ggplot2::theme_bw() +
    ggplot2::theme(
      legend.position = "bottom",
      legend.box = "vertical",
      axis.title = ggplot2::element_blank(),
      legend.title = ggplot2::element_text(size = 20),
      legend.text = ggplot2::element_text(size = 20),
      axis.text.x = ggplot2::element_text(angle = -90, hjust = 0.5, vjust = 0.5, size = 8),
      plot.title = ggplot2::element_text(size = 25, face = "bold"),
      strip.text = ggplot2::element_text(size = 15)
    ) +
    ggplot2::guides(color = ggplot2::guide_legend(override.aes = list(size = 5, fill = NA, linewidth = 1.5)))
}
create_adg_plots <- function(data, responders = NULL, locations = NULL, color_theme = "d3") {
  weight <- lower_lm <- upper_lm <- predicted_weight_lm <- stage <- lm_slope <- r_squared <- stage_days <- 
    adg <- responder <- day_text <- stage_start <- stage_end <- . <- location <- outlier <- NULL
  # 验证颜色主题
  color_scale <- validate_color_theme(color_theme)

  # 验证输入并过滤数据
  validated <- validate_inputs(data, "adg", responders, locations)
  data <- validated$data
  adg_data <- validated$filtered_data

  # 单位转换
  adg_data <- adg_data[, `:=`(
    weight = weight/1000,
    lower_lm = lower_lm/1000,
    upper_lm = upper_lm/1000,
    predicted_weight_lm = predicted_weight_lm/1000
  )]

  # 处理斜率数据
  slopes_data <- data$adg_info[, list(stage, lm_slope, r_squared, stage_days, adg, responder)]
  slopes_data <- slopes_data[, c("stage_start", "stage_end") := {
    split_result <- data.table::tstrsplit(stage, "-", type.convert = TRUE)
    list(as.numeric(split_result[[1]]), as.numeric(split_result[[2]]))
  }]

  if (!is.null(responders)) {
    slopes_data <- slopes_data[responder %in% responders]
  }

  # 创建标注文本
  slopes_data[, day_text := sprintf(
    "Slope: %.2f, R^2: %.2f\n%d~%d kg: %.1f days\nADG: %.2f",
    lm_slope, r_squared, stage_start, stage_end, stage_days, adg
  )]


  # 分组处理
  adg_data <- adg_data[, .(data = list(.SD)), by = location]

  # 生成图形
  adg_data[, plot := purrr::map2(data, location, function(.x, .y) {
    current_slopes <- slopes_data[responder %in% unique(.x$responder)]
    n_responders <- length(unique(.x$responder))

    base_plot <- ggplot2::ggplot(.x, ggplot2::aes(x = date, y = weight)) +
      ggplot2::geom_hline(yintercept = c(30, 60, 120), linetype = "dashed", color = "#666666", alpha = 0.3) +
      ggplot2::geom_ribbon(ggplot2::aes(ymin = lower_lm, ymax = upper_lm), alpha = 0.2) +
      ggplot2::geom_point(ggplot2::aes(color = outlier), size = 1, alpha = 0.8) +
      ggplot2::geom_line(ggplot2::aes(y = predicted_weight_lm, color = "lm prediction"), linewidth = 0.7, alpha = 0.6) +
      ggplot2::facet_wrap(~ as.numeric(responder), ncol = min(2, n_responders)) +
      ggplot2::scale_x_date(date_breaks = "2 day", date_labels = "%m-%d") +
      ggplot2::scale_y_continuous(breaks = seq(15, 135, 15), limits = c(15, 135))

    annotated_plot <- set_common_theme(
      base_plot,
      title = paste("Location:", .y),
      y_lab = "Weight (kg)",
      color_scale = color_scale,
      legend_breaks = c("bound", "outliers", "normal", "predict", "lm prediction"),
      legend_labels = c("outside prediction", "outliers", "normal", "predict", "lm prediction")
    )


    annotated_plot +
      ggplot2::geom_text(
        data = current_slopes,
        ggplot2::aes(x = min(.x$date), y = 135, label = day_text),
        hjust = 0, vjust = 1, size = 3.3
      )
  })]
  cli::cli_alert_success("Successfully created {.field {nrow(adg_data)}} plot{?s}")
  return(adg_data)
}
save_plots <- function(data,
                       save_path,
                       plot_type = c("adg", "adfi"),
                       file_prefix = "loc",
                       file_suffix = NULL,
                       dpi = 300,
                       device = "png") {
  . <- location <- filename <- width <- height <- location <- filename <- NULL

  # 验证并设置 plot_type
  plot_type <- match.arg(plot_type)

  # 根据 plot_type 设置默认的 file_suffix
  if (is.null(file_suffix)) {
    file_suffix <- switch(plot_type,
                          adg = "grow",
                          adfi = "adfi")
  }

  # 参数验证
  if (!inherits(data, "data.table")) {
    cli::cli_abort("Input 'data' must be a data.table")
  }

  if (!all(c("location", "plot", "data") %in% names(data))) {
    cli::cli_abort("Input data must contain 'location', 'plot', and 'data' columns")
  }

  # 验证并创建保存路径
  if (!dir.exists(save_path)) {
    cli::cli_alert_info("Creating directory: {.file {save_path}}")
    dir.create(save_path, recursive = TRUE)
  }

  # 验证其他参数
  supported_devices <- c("png", "pdf", "jpeg", "tiff")
  if (!device %in% supported_devices) {
    cli::cli_abort(c(
      "x" = "Unsupported output device: {device}",
      "i" = "Supported devices: {paste(supported_devices, collapse = ', ')}"
    ))
  }

  cli::cli_process_start("Saving {toupper(plot_type)} plots")

  # 计算图表尺寸和文件名
  save_info <- data[, {
    n_responders <- data.table::uniqueN(data[[1]]$responder)
    n_days <- data.table::uniqueN(data[[1]]$date)
    .(
      width = pmax(0.5 * n_days, 20),
      height = pmax(5 * n_responders, 15),
      filename = file.path(
        save_path,
        paste0(file_prefix, "_", location, "_", file_suffix, ".", device)
      )
    )
  }, by = location]

  # 创建进度条
  pb <- cli::cli_progress_bar(
    format = paste0(
      "{cli::pb_spin} Saving ",
      cli::col_blue("{.emph {file_prefix}_{location}_{file_suffix}.{device}}"),
      " [{cli::pb_current}/{cli::pb_total}] | ETA:{cli::pb_eta}"
    ),
    total = nrow(data)
  )

  # 合并信息并保存图表
  results <- save_info[data, on = "location"][, {
    # 使用 data.table 逐行处理
    result <- .SD[, {
      tryCatch({
        ggplot2::ggsave(
          filename = filename,
          plot = plot[[1]],
          width = width,
          height = height,
          units = "cm",
          dpi = dpi,
          device = device
        )
        cli::cli_progress_update(id = pb)
        list(
          location = location,
          filename = filename,
          success = TRUE
        )
      }, error = function(e) {
        cli::cli_alert_danger("Error saving plot for location {.field {cli::col_red(location)}}: {e$message}")
        list(
          location = location,
          filename = filename,
          success = FALSE
        )
      })
    }, by = location, showProgress = FALSE]
    result
  }]

  # 完成进度条
  cli::cli_progress_done(id = pb)

  # 统计和显示最终结果
  success_count <- sum(results$success)
  total_count <- nrow(results)

  if (success_count == total_count) {
    cli::cli_alert_success("Successfully saved all plots to {.file {save_path}}")
  } else {
    cli::cli_alert_warning(
      "Saved {.field {cli::col_red(success_count)}} out of {.field {cli::col_red(total_count)}} plots to {.file {save_path}}"
    )
  }

  cli::cli_process_done()
  #cli::cli_alert_success("Successfully created {toupper(plot_type)} plots")

  # 返回结果
  invisible(results)
}
