# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Calculate Feed Conversion Ratio (FCR)
#'
#' @description
#' Calculates Feed Conversion Ratio (FCR) based on Average Daily Gain (ADG) and Average Daily Feed Intake (ADFI) data.
#' This function merges ADG and ADFI data, calculates corrected FCR values, and generates statistical summaries.
#'
#' @param adg_res A list object returned by the `adg_get()` function, containing ADG data and related information.
#' @param adfi_res A list object returned by the `adfi_get()` function, containing ADFI data and related information.
#' @param quiet Logical; if TRUE, suppresses all messages and warnings, default is FALSE.
#'
#' @return A list containing:
#' \itemize{
#'   \item `fcr_res`: A data.table with FCR calculation results
#'   \item `adg_info`: The input ADG information table
#'   \item `adg_data`: The original ADG data
#'   \item `adfi_info`: The input ADFI information table
#'   \item `adfi_data`: The original ADFI data
#'   \item `fcr_summary`: Statistical summary of FCR calculation results
#' }
#'
#' @details
#' The `fcr_get` function performs the following steps:
#' \itemize{
#'   \item Validates the format of input ADG and ADFI data
#'   \item Merges ADG and ADFI data, matching by animal ID and location
#'   \item Calculates corrected daily gain and feed conversion ratio
#'   \item Generates statistical summaries of FCR, including sample size, minimum, maximum, median, mean, standard deviation, and coefficient of variation
#' }
#'
#' @seealso
#' \code{\link{adg_get}} for calculating Average Daily Gain data
#' \code{\link{adfi_get}} for calculating Average Daily Feed Intake data
#'
#' @importFrom cli cli_h1 cli_process_start cli_process_done cli_process_failed cli_abort cli_alert_info cli_alert_success
#' @importFrom data.table setkeyv :=
#'
#' @export
#' @examples
#' result_nedap <- preprocess_data(data = mintyr::nedap, station_type = "nedap", quiet = TRUE)
#' adg_result <- adg_get(result_nedap, my_break = c(30,120), quiet = TRUE)
#' adfi_result <- adfi_get(result_nedap, adg_result, quiet = TRUE)
#' fcr_result <- fcr_get(adg_res = adg_result, adfi_res = adfi_result, quiet = TRUE)
#' head(fcr_result$fcr_res)
#' head(fcr_result$fcr_summary)
fcr_get <- function(adg_res, adfi_res, quiet = FALSE) {
  corrected_adg <- lm_slope <- adg <- cor_fcr <- corrected_dfi <- NULL
  # 定义处理函数，根据quiet参数决定是否抑制消息和警告
  process_fn <- if (quiet) {
    function(expr) suppressMessages(suppressWarnings(expr))
  } else {
    function(expr) expr
  }

  # 使用process_fn包装主要处理逻辑
  result <- process_fn({
    cli::cli_h1("Calculating FCR")

    # 验证输入参数
    cli::cli_process_start("Validating input ADG data")
    if (!is.list(adg_res) || !all(c("adg_info", "adg_data") %in% names(adg_res))) {
      cli::cli_process_failed()
      cli::cli_abort("adg_res must be the output from adg_get() function")
    }
    cli::cli_process_done()
    cli::cli_process_start("Validating input ADFI data")
    if (!is.list(adfi_res) || !all(c("adfi_info", "adfi_data") %in% names(adfi_res))) {
      cli::cli_process_failed()
      cli::cli_abort("adfi_res must be the output from adfi_get() function")
    }

    if (!data.table::is.data.table(adg_res$adg_info) || !data.table::is.data.table(adfi_res$adfi_info)) {
      cli::cli_process_failed()
      cli::cli_abort("adg_info and adfi_info must be data.tables")
    }
    cli::cli_process_done()

    # 准备数据
    cli::cli_process_start("Preparing data for FCR calculation")
    dt1 <- adg_res$adg_info
    dt2 <- adfi_res$adfi_info

    data.table::setkeyv(dt1, c("responder", "location"))
    data.table::setkeyv(dt2, c("responder", "location"))

    # 合并数据
    cli::cli_alert_info("Merging ADG and ADFI data")
    joined_dt <- dt1[dt2, nomatch = 0]

    # 计算动物数量
    animal_count <- nrow(joined_dt)
    location_count <- length(unique(joined_dt$location))
    cli::cli_alert_info("Found {.val {animal_count}} animals across {.val {location_count}} locations")
    cli::cli_process_done()

    # 计算FCR
    cli::cli_process_start("Calculating FCR values")
    joined_dt[, `:=`(corrected_adg, (lm_slope + adg) / 2)
    ][, `:=`(cor_fcr, corrected_dfi/corrected_adg)]

    # 如果存在stage列，计算校正FCR(因预测了体重范围内所有体重与采食量，所以不需要再次校正)
    # if ("stage" %in% colnames(joined_dt)) {
    #   cli::cli_alert_info("Calculating corrected FCR based on stage information")
    #   stage_values <- as.numeric(unlist(strsplit(unique(joined_dt$stage), "-")))
    #   joined_dt[, `:=`(cor_fcr, fcr +
    #                      (stage_values[1] - min_weight_cut/1000) * 0.005 +
    #                      (stage_values[2] - max_weight_cut/1000) * 0.005)]
    # }
    cli::cli_process_done()

    # 计算FCR统计摘要
    cli::cli_process_start("Generating FCR summary statistics")
    fcr_results_stats <- fcr_summary(joined_dt)
    cli::cli_process_done()

    # 创建结果列表
    result_list <- list(
      fcr_res = joined_dt,
      adg_info = dt1,
      adg_data = adg_res$adg_data,
      adfi_info = dt2,
      adfi_data = adfi_res$adfi_data,
      fcr_summary = fcr_results_stats
    )

    cli::cli_alert_success("FCR calculation completed successfully")

    return(result_list)
  })

  return(result)
}
# Helper function to process data
process_fcr_data <- function(data) {
  ..common_cols <- NULL
  # Determine column names
  common_cols <- c("min_weight_cut", "max_weight_cut", "lm_slope", "stage_days", "adg", "corrected_dfi", "cor_fcr")  # Define common columns

  # Perform operations on these columns in data
  data <- data[, ..common_cols]  # Select only the chosen columns from the data

  # Find all columns that contain "weight"
  weight_cols <- grep("weight", names(data), value = TRUE)

  # Divide all values in these columns by 1000
  data[, (weight_cols) := lapply(.SD, function(x) x / 1000), .SDcols = weight_cols][]

  return(data)  # Return the processed data
}
# Helper function to calculate statistics
fcr_data_stats <- function(data) {
  # Calculate statistics for each column in the data
  stats <- data[, lapply(.SD, function(x) {
    list(
      N = sum(!is.na(x)),  # Number of non-NA values
      min = min(x, na.rm = TRUE),  # Minimum value, ignoring NA
      max = max(x, na.rm = TRUE),  # Maximum value, ignoring NA
      median = stats::median(x, na.rm = TRUE),  # Median value, ignoring NA
      mean = mean(x, na.rm = TRUE),  # Mean value, ignoring NA
      sd = stats::sd(x, na.rm = TRUE),  # Standard deviation, ignoring NA
      cv = stats::sd(x, na.rm = TRUE) / mean(x, na.rm = TRUE)  # Coefficient of variation (CV)
    )
  })]

  return(stats)  # Return the calculated statistics
}
# FCR results summary
fcr_summary <- function(data) {
  cv <- N <- NULL

  # Process data and calculate statistics
  fcr_stats <- process_fcr_data(data) |>
    fcr_data_stats()

  fcr_summary_data <- data.table::data.table(t(fcr_stats))

  data.table::setnames(fcr_summary_data, c("N", "min", "max", "median", "mean", "sd", "cv"))

  fcr_summary_data$traits <- colnames(fcr_stats)

  data.table::setcolorder(fcr_summary_data, c("traits", setdiff(names(fcr_summary_data), "traits")))

  num_cols <- c("N", "min", "max", "median", "mean", "sd", "cv")
  fcr_summary_data[, (num_cols) := lapply(.SD, function(x) as.numeric(unlist(x))), .SDcols = num_cols]


  fcr_summary_data[, cv := sprintf("%.2f%%", round(cv * 100, 2))][, N := as.character(N)]

  numeric_cols <- names(fcr_summary_data)[sapply(fcr_summary_data, is.numeric)]
  fcr_summary_data[, (numeric_cols) := lapply(.SD, function(x) sprintf("%0.2f", as.numeric(x))), .SDcols = numeric_cols][]

  return(fcr_summary_data)
}
