# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Import Nedap Data CSV Files
#'
#' @description
#' Imports and combines data from multiple Nedap data csv files using either the data.table or vroom package.
#' This function provides a flexible way to read and merge multiple data files with consistent formatting.
#'
#' @param filepaths A character vector of file paths to the Nedap data files to be imported.
#' @param package Character string specifying which package to use for importing; either "data.table" or "vroom". Default is "data.table".
#' @param ... Additional arguments passed to the underlying import function (data.table::fread or vroom::vroom).
#'
#' @return A data.table or tibble (depending on the package used) containing the combined data from all imported files.
#'
#' @details
#' The `import_nedap` function performs the following steps:
#' \itemize{
#'   \item Validates that all specified file paths exist
#'   \item Checks that the requested package is installed and supported
#'   \item Imports all files using the specified method
#'   \item Combines all imported data into a single data structure
#' }
#'
#' When using "data.table" as the package, files are read individually with fread() and combined with rbindlist().
#' When using "vroom", all files are read at once using vroom's multi-file capability.
#'
#' @seealso
#' \code{\link[data.table]{fread}} for data.table's file reading function
#' \code{\link[vroom]{vroom}} for vroom's file reading function
#'
#' @importFrom cli cli_abort cli_alert_info cli_alert_success
#' @importFrom data.table rbindlist
#' @importFrom purrr map
#'
#' @export
#' @examples
#' # Example: CSV file import demonstrations
#'
#' # Setup test files
#' csv_files <- mintyr::mintyr_example(
#'   mintyr::mintyr_examples("csv_test")     # Get example CSV files
#' )
#'
#' import_nedap(filepaths = csv_files)
import_nedap <- function (filepaths, package = "data.table", ...) {
  # Check if filepaths is provided and is a valid vector of file paths
  if (missing(filepaths) || is.null(filepaths) || !is.character(filepaths) || !all(file.exists(filepaths))) {
    cli::cli_abort("filepaths must be a vector of existing file paths.")
  }
  
  # Check if package is valid
  if (!is.character(package) || !package %in% c("data.table", "vroom")) {
    cli::cli_abort("package must be one of 'data.table', 'vroom'.")
  }
  
  # Check if package is installed and can be loaded
  if (!requireNamespace(package, quietly = TRUE)) {
    cli::cli_abort("Package '{package}' could not be loaded. Please install it.")
  }
  
  # Import data based on the selected package
  result <- switch(
    package,
    data.table = {
      cli::cli_alert_info("Using package {.pkg data.table} to import {length(filepaths)} files.")
      data.table::rbindlist(purrr::map(filepaths, function(x, ...) {
        data.table::fread(x, ...)
      }, ...))
    },
    vroom = {
      cli::cli_alert_info("Using package {.pkg vroom} to import {length(filepaths)} files.")
      vroom::vroom(filepaths, ...)
    },
    {
      # This should not be reached due to package validation, but as a fallback
      cli::cli_abort("Invalid package specified.")
      invisible(NULL)
    }
  )
  cli::cli_alert_success("Successfully imported data from {length(filepaths)} files")
  return(result)
}
